# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipC', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('maidenName', models.CharField(blank=True, default='', max_length=100)),
                ('birthday', models.DateField()),
            ],
            managers=[
                ('usermanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
