# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_id',
            field=models.CharField(max_length=20),
        ),
    ]
