# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20161111_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.Messages'),
        ),
    ]
